// scripts/build_turn_function.mjs — emits functions/turn.built.js: the /turn
// serverless function with prompts/turn.md and all packs INLINED, so the deployed
// function and the eval harness share the exact same template file (single source
// of truth in the repo). Re-run after any change to prompts/turn.md or a pack,
// then redeploy.
// Usage: node scripts/build_turn_function.mjs

import { readFileSync, writeFileSync, readdirSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const template = readFileSync(join(root, "prompts", "turn.md"), "utf8");
const openerTemplate = readFileSync(join(root, "prompts", "opener.md"), "utf8");
const personas = JSON.parse(readFileSync(join(root, "packs", "personas.json"), "utf8"));

const packs = {};
for (const f of readdirSync(join(root, "packs"))) {
  if (!f.endsWith(".json")) continue;
  const pack = JSON.parse(readFileSync(join(root, "packs", f), "utf8"));
  if (!pack.id || !pack.misconceptions) continue;   // only concept packs
  packs[pack.id] = pack;
}

const code = `// AUTO-GENERATED by scripts/build_turn_function.mjs — do not edit by hand.
// Edit prompts/turn.md, prompts/opener.md, or packs/*.json, rebuild, redeploy.
const TEMPLATE = ${JSON.stringify(template)};
const OPENER_TEMPLATE = ${JSON.stringify(openerTemplate)};
const PACKS = ${JSON.stringify(packs)};
const PERSONAS = ${JSON.stringify(personas.personas)};
const DEFAULT_LEVEL = ${JSON.stringify(personas.default)};

const CLASSROOM_OVERRIDE = [
  "",
  "## CLASSROOM MODE OVERRIDE (applies to THIS session)",
  "",
  "Instead of one Milo, JOB 2 voices a small class of three students being taught together.",
  "Each student PERSONALLY holds exactly one misconception and no other:",
  "- Zoe — confident, talks fast, states her wrong beliefs as facts. She holds m1 only.",
  "- Sam — quiet, thinks in pictures, needs concrete examples. He holds m2 only.",
  "- Ravi — quick and curious, asks 'but why' a lot. He holds m3 only.",
  "Rules:",
  "- Replace the \\"milo\\" output field with \\"class\\": an array of 1-2 entries",
  "  [{\\"name\\": \\"Zoe\\"|\\"Sam\\"|\\"Ravi\\", \\"reply\\": \\"...\\", \\"mood\\": \\"confused\\"|\\"thinking\\"|\\"clicking\\"|\\"aha\\"}].",
  "- Who speaks: first, any student whose misconception was resolved THIS turn shows their click (mood clicking/aha).",
  "  Then the student holding the LOWEST-numbered still-unresolved misconception voices their confusion or probe.",
  "  Maximum 2 speakers per turn. Never all three at once.",
  "- A student whose misconception is resolved never explains the mechanism to the others — they can cheer",
  "  (\\"ohh I get it now!!\\") but the TEACHER must do the teaching. Unresolved students stay genuinely confused.",
  "- A student NEVER voices a confusion they don't hold. If the next unresolved confusion belongs to a",
  "  different student, THAT student speaks as the second entry — never merge two students' confusions into one voice.",
  "- All evaluator rules, phase logic, and HARD BANS apply unchanged to every student's reply.",
  "- force_check: the student holding the lowest unresolved misconception attempts the check problem and fails per its failure_mode.",
  "- If ALL are resolved: the class has its aha together (2 entries max), one restates, one nails the check problem."
].join("\\n");

const CORS = {
  "access-control-allow-origin": "*",
  "access-control-allow-methods": "POST, OPTIONS",
  "access-control-allow-headers": "content-type, authorization"
};

function json(obj, status) {
  return new Response(JSON.stringify(obj), {
    status,
    headers: { "content-type": "application/json", ...CORS }
  });
}

export default async function handler(req, ctx) {
  if (req.method === "OPTIONS") return new Response(null, { status: 204, headers: CORS });
  if (req.method !== "POST") return json({ error: "POST only" }, 405);
  try {
    const { opener, transcribe, image, pack_id, pack: dynamicPack, state, transcript, student_turn, learner_memory, learner_name, milo_level, classroom, agent_name, agent_persona } = await req.json();

    // Transcribe mode: handwriting from the drawing canvas -> plain text (vision call).
    if (transcribe) {
      if (!image || !image.startsWith("data:image/")) return json({ error: "image data URI required" }, 400);
      const tRes = await fetch(
        ctx.env.BUTTERBASE_API_URL + "/v1/" + ctx.env.BUTTERBASE_APP_ID + "/chat/completions",
        {
          method: "POST",
          headers: { "content-type": "application/json", authorization: "Bearer " + ctx.env.BUTTERBASE_API_KEY },
          body: JSON.stringify({
            model: "anthropic/claude-sonnet-4.6", max_tokens: 500, temperature: 0,
            messages: [{ role: "user", content: [
              { type: "text", text: "This is a student's whiteboard. Read EVERYTHING on it \\u2014 both handwriting and drawings \\u2014 and produce the message the student is communicating, as plain text.\\n- Transcribe handwritten words exactly. Preserve math in typed notation (3/4, 1/2, divided by or \\u00f7, \\u00d7, =, \\u00b0 for degrees).\\n- Describe every drawn shape or diagram inline in brackets where it appears, faithfully and concretely: what shape it is, its orientation, and every label, angle mark, arrow, or measurement attached to it and WHERE each sits. Example: [drawing: a right triangle \\u2014 the right angle is marked with a small square at the bottom-right corner, a 30\\u00b0 angle is labeled at the bottom-left, and the slanted side runs from bottom-left up to top-right].\\n- Do not interpret, grade, or explain \\u2014 just report what is written and drawn so someone who cannot see the board fully understands it.\\nOutput ONLY the transcription with bracketed drawing descriptions \\u2014 no commentary, no quotes. If a word is hard to read, make your best guess from context." },
              { type: "image_url", image_url: { url: image } }
            ]}]
          })
        }
      );
      if (!tRes.ok) return json({ error: "gateway " + tRes.status }, 502);
      const tData = await tRes.json();
      const text = ((tData.choices && tData.choices[0] && tData.choices[0].message.content) || "").trim();
      if (!text) return json({ error: "could not read the handwriting" }, 502);
      return json({ text }, 200);
    }

    // Built-in packs by id; generated topic packs arrive inline in the request.
    const pack = PACKS[pack_id] || (dynamicPack && dynamicPack.misconceptions ? dynamicPack : null);
    if (!pack) return json({ error: "unknown pack: " + pack_id }, 400);
    // Agent identity: an EverMind learner persona overrides the generic level persona,
    // and the agent's name replaces "Milo" throughout the prompt (fn-side only — the
    // eval harness still pins the default Milo persona).
    const persona = agent_persona || PERSONAS[milo_level] || PERSONAS[DEFAULT_LEVEL];
    const rename = t => (agent_name && agent_name !== "Milo") ? t.split("Milo").join(agent_name) : t;

    // Opener mode: Milo's first line, memory-aware. No evaluator, no state change.
    if (opener) {
      const oPrompt = rename(OPENER_TEMPLATE
        .replace("{{PACK_JSON}}", JSON.stringify(pack, null, 2))
        .replace("{{MILO_PERSONA}}", persona)
        .replace("{{LEARNER_MEMORY}}", JSON.stringify(learner_memory || []))
        .replace("{{LEARNER_NAME}}", learner_name || "the student"));
      const oRes = await fetch(
        ctx.env.BUTTERBASE_API_URL + "/v1/" + ctx.env.BUTTERBASE_APP_ID + "/chat/completions",
        {
          method: "POST",
          headers: { "content-type": "application/json", authorization: "Bearer " + ctx.env.BUTTERBASE_API_KEY },
          body: JSON.stringify({
            model: "anthropic/claude-sonnet-4.6", max_tokens: 300, temperature: 0.4,
            messages: [{ role: "user", content: oPrompt }]
          })
        }
      );
      if (!oRes.ok) return json({ error: "gateway " + oRes.status }, 502);
      const oData = await oRes.json();
      const oText = (oData.choices && oData.choices[0] && oData.choices[0].message.content) || "";
      const oClean = oText.replace(/\\u0060\\u0060\\u0060json/gi, "").replace(/\\u0060\\u0060\\u0060/g, "").trim();
      const oOut = JSON.parse(oClean.slice(oClean.indexOf("{"), oClean.lastIndexOf("}") + 1));
      if (!oOut.milo || !oOut.milo.reply) return json({ error: "opener missing milo.reply" }, 502);
      return json(oOut, 200);
    }

    if (!state || !student_turn) return json({ error: "state and student_turn are required" }, 400);

    const prompt = rename(TEMPLATE
      .replace("{{PACK_JSON}}", JSON.stringify(pack, null, 2))
      .replace("{{MILO_PERSONA}}", persona)
      .replace("{{STATE_JSON}}", JSON.stringify(state, null, 2))
      .replace("{{LEARNER_MEMORY}}", JSON.stringify(learner_memory || []))
      .replace("{{TRANSCRIPT}}", transcript || "(start of session)")
      .replace("{{STUDENT_TURN}}", student_turn))
      + (classroom ? "\\n" + CLASSROOM_OVERRIDE : "");

    const res = await fetch(
      ctx.env.BUTTERBASE_API_URL + "/v1/" + ctx.env.BUTTERBASE_APP_ID + "/chat/completions",
      {
        method: "POST",
        headers: {
          "content-type": "application/json",
          authorization: "Bearer " + ctx.env.BUTTERBASE_API_KEY
        },
        body: JSON.stringify({
          model: "anthropic/claude-sonnet-4.6",
          max_tokens: 1400,
          temperature: 0.3,
          messages: [{ role: "user", content: prompt }]
        })
      }
    );
    if (!res.ok) return json({ error: "gateway " + res.status + ": " + (await res.text()) }, 502);

    const data = await res.json();
    const text = (data.choices && data.choices[0] && data.choices[0].message.content) || "";
    const cleaned = text.replace(/\\u0060\\u0060\\u0060json/gi, "").replace(/\\u0060\\u0060\\u0060/g, "").trim();
    const out = JSON.parse(cleaned.slice(cleaned.indexOf("{"), cleaned.lastIndexOf("}") + 1));
    const speakerOk = classroom
      ? Array.isArray(out.class) && out.class.length && out.class.every(c => c.name && c.reply)
      : out.milo && out.milo.reply;
    if (!out.evaluation || !out.updated_state || !speakerOk)
      return json({ error: "model output missing required fields", raw: text.slice(0, 400) }, 502);
    return json({ ...out, _usage: data.usage }, 200);
  } catch (err) {
    return json({ error: String((err && err.message) || err) }, 500);
  }
}
`;

mkdirSync(join(root, "functions"), { recursive: true });
writeFileSync(join(root, "functions", "turn.built.js"), code);
console.log(`functions/turn.built.js written (${code.length} bytes, packs: ${Object.keys(packs).join(", ")})`);
