// scripts/build_report_function.mjs — emits functions/report.built.js with
// prompts/report.md and all packs inlined (same single-source-of-truth pattern as
// build_turn_function.mjs). Re-run + redeploy after editing prompts/report.md.
// Usage: node scripts/build_report_function.mjs

import { readFileSync, writeFileSync, readdirSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const template = readFileSync(join(root, "prompts", "report.md"), "utf8");

const packs = {};
for (const f of readdirSync(join(root, "packs"))) {
  if (!f.endsWith(".json")) continue;
  const pack = JSON.parse(readFileSync(join(root, "packs", f), "utf8"));
  if (!pack.id || !pack.misconceptions) continue;   // only concept packs
  packs[pack.id] = pack;
}

const code = `// AUTO-GENERATED by scripts/build_report_function.mjs — do not edit by hand.
const TEMPLATE = ${JSON.stringify(template)};
const PACKS = ${JSON.stringify(packs)};

const CORS = {
  "access-control-allow-origin": "*",
  "access-control-allow-methods": "POST, OPTIONS",
  "access-control-allow-headers": "content-type, authorization"
};

function json(obj, status) {
  return new Response(JSON.stringify(obj), {
    status,
    headers: { "content-type": "application/json", ...CORS }
  });
}

export default async function handler(req, ctx) {
  if (req.method === "OPTIONS") return new Response(null, { status: 204, headers: CORS });
  if (req.method !== "POST") return json({ error: "POST only" }, 405);
  try {
    const { pack_id, pack: dynamicPack, state, transcript, learner_memory, learner_name, agent_name } = await req.json();
    const pack = PACKS[pack_id] || (dynamicPack && dynamicPack.misconceptions ? dynamicPack : null);
    if (!pack) return json({ error: "unknown pack: " + pack_id }, 400);
    const rename = t => (agent_name && agent_name !== "Milo") ? t.split("Milo").join(agent_name) : t;
    if (!state || !transcript) return json({ error: "state and transcript are required" }, 400);

    const date = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
    const prompt = rename(TEMPLATE
      .replace("{{PACK_JSON}}", JSON.stringify(pack, null, 2))
      .replace("{{STATE_JSON}}", JSON.stringify(state, null, 2))
      .replace("{{TRANSCRIPT}}", transcript)
      .replace("{{LEARNER_MEMORY}}", JSON.stringify(learner_memory || []))
      .replace("{{LEARNER_NAME}}", learner_name || "Student")
      .replace("{{CONCEPT_TITLE}}", pack.title)
      .replace("{{DATE}}", date));

    const res = await fetch(
      ctx.env.BUTTERBASE_API_URL + "/v1/" + ctx.env.BUTTERBASE_APP_ID + "/chat/completions",
      {
        method: "POST",
        headers: {
          "content-type": "application/json",
          authorization: "Bearer " + ctx.env.BUTTERBASE_API_KEY
        },
        body: JSON.stringify({
          model: "anthropic/claude-sonnet-4.6",
          max_tokens: 1200,
          temperature: 0.2,
          messages: [{ role: "user", content: prompt }]
        })
      }
    );
    if (!res.ok) return json({ error: "gateway " + res.status + ": " + (await res.text()) }, 502);

    const data = await res.json();
    const report = ((data.choices && data.choices[0] && data.choices[0].message.content) || "")
      .replace(/^\\s*\\u0060\\u0060\\u0060(markdown)?/i, "").replace(/\\u0060\\u0060\\u0060\\s*$/, "").trim();
    if (!report) return json({ error: "empty report from model" }, 502);
    return json({ report, _usage: data.usage }, 200);
  } catch (err) {
    return json({ error: String((err && err.message) || err) }, 500);
  }
}
`;

mkdirSync(join(root, "functions"), { recursive: true });
writeFileSync(join(root, "functions", "report.built.js"), code);
console.log(`functions/report.built.js written (${code.length} bytes)`);
