// scripts/build_learn_function.mjs — emits functions/learn.built.js
// One function, five ops (POST {op, ...}):
//   chapter    {topic?|text?, grade_band?} -> wiki fetch (topic mode) -> LLM structure
//              -> insert chapter+topics (ctx.db) -> Neo4j graph MERGE -> {chapter_id}
//   illustrate {topic_id} -> image model -> save data URI on topic -> {image}
//   pack       {topic_id} -> prompts/pack_generator.md -> save pack on topic -> {pack}
//   mastered   {topic_id} -> mark mastered in DB + Neo4j
//   next       {} -> Neo4j: unmastered topics whose prereqs are all mastered
// Usage: node scripts/build_learn_function.mjs

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const packGen = readFileSync(join(root, "prompts", "pack_generator.md"), "utf8");
const examplePack = readFileSync(join(root, "packs", "fractions_division.json"), "utf8");

const code = `// AUTO-GENERATED by scripts/build_learn_function.mjs — do not edit by hand.
const PACK_GEN_TEMPLATE = ${JSON.stringify(packGen)};
const EXAMPLE_PACK = ${JSON.stringify(JSON.parse(examplePack))};

const CORS = {
  "access-control-allow-origin": "*",
  "access-control-allow-methods": "POST, OPTIONS",
  "access-control-allow-headers": "content-type, authorization"
};
function json(obj, status) {
  return new Response(JSON.stringify(obj), { status, headers: { "content-type": "application/json", ...CORS } });
}

async function llm(ctx, messages, opts) {
  const res = await fetch(ctx.env.BUTTERBASE_API_URL + "/v1/" + ctx.env.BUTTERBASE_APP_ID + "/chat/completions", {
    method: "POST",
    headers: { "content-type": "application/json", authorization: "Bearer " + ctx.env.BUTTERBASE_API_KEY },
    body: JSON.stringify(Object.assign({ model: "anthropic/claude-sonnet-4.6", messages }, opts || {}))
  });
  if (!res.ok) throw new Error("gateway " + res.status + ": " + (await res.text()).slice(0, 200));
  return res.json();
}

function parseJson(text) {
  const cleaned = text.replace(/\\u0060\\u0060\\u0060json/gi, "").replace(/\\u0060\\u0060\\u0060/g, "").trim();
  return JSON.parse(cleaned.slice(cleaned.indexOf("{"), cleaned.lastIndexOf("}") + 1));
}

async function cypher(ctx, statement, parameters) {
  try {
    const res = await fetch("https://" + ctx.env.NEO4J_HOST + "/db/" + ctx.env.NEO4J_DB + "/query/v2", {
      method: "POST",
      headers: { "content-type": "application/json", authorization: "Basic " + ctx.env.NEO4J_AUTH },
      body: JSON.stringify({ statement, parameters: parameters || {} })
    });
    const data = await res.json();
    if (!res.ok || data.errors) console.warn("neo4j:", JSON.stringify(data).slice(0, 300));
    return data.data || null;
  } catch (err) {
    console.warn("neo4j unreachable:", err.message);   // graph is enrichment, never fatal
    return null;
  }
}

async function opChapter(ctx, body) {
  const gradeBand = body.grade_band || "6-8";
  let source = (body.text || "").slice(0, 24000);
  let sourceKind = source ? "pasted text" : "model knowledge";

  // Topic mode: pull real chapter material from Wikipedia when we can.
  if (!source && body.topic) {
    try {
      const wiki = await fetch(
        "https://en.wikipedia.org/w/api.php?action=query&prop=extracts&explaintext=1&exintro=0&format=json&origin=*&redirects=1&titles=" +
        encodeURIComponent(body.topic)
      ).then(r => r.json());
      const pages = wiki?.query?.pages || {};
      const page = Object.values(pages)[0];
      if (page && page.extract) {
        source = page.extract.slice(0, 24000);
        sourceKind = "Wikipedia: " + page.title;
      }
    } catch (err) { console.warn("wikipedia fetch failed:", err.message); }
  }
  if (!source && !body.topic) return json({ error: "provide topic or text" }, 400);

  const nTopics = body.topic_count >= 3 && body.topic_count <= 8 ? "EXACTLY " + body.topic_count : "EXACTLY 4 to 6";
  const prompt = [
    "You are building a study chapter for a learning app where students learn topics and then prove understanding by TEACHING them.",
    "TOPIC: " + (body.topic || "derive from the source material"),
    "GRADE BAND: " + gradeBand + " (pitch all language at this level; simple words, concrete examples)",
    "SOURCE MATERIAL (" + sourceKind + "; may be partial — fill gaps from your own knowledge, but never contradict the source):",
    "<<<", source || "(none — use your own knowledge)", ">>>",
    "",
    "Produce a JSON object EXACTLY like:",
    '{"chapter_title": "...", "topics": [{"title": "...", "key_idea": "one punchy sentence", "summary": "2-3 simple sentences", "explanation": "4-7 sentences in easy words with ONE concrete worked example or analogy", "illustration_prompt": "a purely visual scene for an educational sketch, described concretely, NO text/letters/numbers in the scene", "prereqs": [0-based indices of topics in THIS list that should be understood first]}]}',
    "Rules: " + nTopics + " topics, ordered so prerequisites come first. prereqs only reference EARLIER topics. Every topic must be genuinely learnable from its explanation alone. Output ONLY the JSON."
  ].join("\\n");

  const data = await llm(ctx, [{ role: "user", content: prompt }], { max_tokens: 3500, temperature: 0.3 });
  const out = parseJson(data.choices[0].message.content || "");
  if (!out.chapter_title || !Array.isArray(out.topics) || out.topics.length < 3)
    return json({ error: "chapter generation came back malformed — try again" }, 502);

  const ch = await ctx.db.query(
    "INSERT INTO chapters (title, source, grade_band) VALUES ($1, $2, $3) RETURNING id",
    [out.chapter_title, sourceKind, gradeBand]
  );
  const chapterId = ch.rows[0].id;

  const topicIds = [];
  for (let i = 0; i < out.topics.length; i++) {
    const t = out.topics[i];
    const r = await ctx.db.query(
      "INSERT INTO topics (chapter_id, position, title, key_idea, summary, explanation, illustration_prompt, prereqs) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id",
      [chapterId, i, t.title, t.key_idea || "", t.summary || "", t.explanation || "", t.illustration_prompt || t.title, JSON.stringify((t.prereqs || []).filter(p => p >= 0 && p < i))]
    );
    topicIds.push(r.rows[0].id);
  }

  // Graph: Chapter -> HAS_TOPIC -> Topic, Topic -REQUIRED_FOR-> Topic
  await cypher(ctx,
    "MERGE (c:Chapter {id: $cid}) SET c.title = $title " +
    "WITH c UNWIND $topics AS t " +
    "MERGE (n:Topic {id: t.id}) ON CREATE SET n.mastered = false " +
    "SET n.title = t.title, n.position = t.position, n.chapter = $title " +
    "MERGE (c)-[:HAS_TOPIC]->(n)",
    { cid: chapterId, title: out.chapter_title,
      topics: out.topics.map((t, i) => ({ id: topicIds[i], title: t.title, position: i })) }
  );
  const edges = [];
  out.topics.forEach((t, i) => (t.prereqs || []).forEach(p => {
    if (p >= 0 && p < i) edges.push({ from: topicIds[p], to: topicIds[i] });
  }));
  if (edges.length)
    await cypher(ctx,
      "UNWIND $edges AS e MATCH (a:Topic {id: e.from}), (b:Topic {id: e.to}) MERGE (a)-[:REQUIRED_FOR]->(b)",
      { edges });

  return json({ chapter_id: chapterId, title: out.chapter_title, source: sourceKind, topic_count: out.topics.length }, 200);
}

// Grow a course from NEW MATERIAL (another chapter pasted/uploaded): generates 2-4
// additional topics that extend — never duplicate — the existing ones, wired into
// the same prerequisite graph.
async function opExtend(ctx, body) {
  if (!body.chapter_id || !body.text) return json({ error: "chapter_id and text required" }, 400);
  const ch = await ctx.db.query("SELECT id, title, grade_band FROM chapters WHERE id = $1", [body.chapter_id]);
  if (!ch.rows.length) return json({ error: "chapter not found" }, 404);
  const existing = await ctx.db.query(
    "SELECT id, position, title, key_idea FROM topics WHERE chapter_id = $1 ORDER BY position", [body.chapter_id]);
  const base = existing.rows.length ? Math.max(...existing.rows.map(r => r.position)) + 1 : 0;

  const prompt = [
    "You are growing an existing course titled \\"" + ch.rows[0].title + "\\" (grade band " + ch.rows[0].grade_band + ") with NEW MATERIAL.",
    "EXISTING topics (position: title — key idea):",
    existing.rows.map(t => t.position + ": " + t.title + " — " + t.key_idea).join("\\n"),
    "NEW MATERIAL:",
    "<<<", body.text.slice(0, 24000), ">>>",
    "",
    "Produce 2 to 4 NEW topics covering what the material adds. Never restate an existing topic.",
    "Output EXACTLY:",
    '{"topics": [{"title": "...", "key_idea": "one punchy sentence", "summary": "2-3 simple sentences", "explanation": "4-7 sentences, easy words, ONE concrete example", "illustration_prompt": "purely visual scene, NO text in it", "prereqs": [positions this depends on — may reference EXISTING positions above, or earlier NEW topics as ' + base + ', ' + (base + 1) + ', ...]}]}',
    "Order new topics so prerequisites come first. Output ONLY the JSON."
  ].join("\\n");
  const data = await llm(ctx, [{ role: "user", content: prompt }], { max_tokens: 2500, temperature: 0.3 });
  const out = parseJson(data.choices[0].message.content || "");
  if (!Array.isArray(out.topics) || !out.topics.length) return json({ error: "extension came back malformed" }, 502);

  const posToId = {};
  existing.rows.forEach(r => { posToId[r.position] = r.id; });
  const added = [];
  for (let i = 0; i < out.topics.length; i++) {
    const t = out.topics[i];
    const pos = base + i;
    const prereqs = (t.prereqs || []).filter(p => p >= 0 && p < pos && (posToId[p] || p >= base));
    const r = await ctx.db.query(
      "INSERT INTO topics (chapter_id, position, title, key_idea, summary, explanation, illustration_prompt, prereqs) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id",
      [body.chapter_id, pos, t.title, t.key_idea || "", t.summary || "", t.explanation || "", t.illustration_prompt || t.title, JSON.stringify(prereqs)]);
    posToId[pos] = r.rows[0].id;
    added.push({ id: r.rows[0].id, title: t.title, position: pos, prereqs });
  }

  await cypher(ctx,
    "MATCH (c:Chapter {id: $cid}) UNWIND $topics AS t MERGE (n:Topic {id: t.id}) ON CREATE SET n.mastered = false " +
    "SET n.title = t.title, n.position = t.position, n.chapter = c.title MERGE (c)-[:HAS_TOPIC]->(n)",
    { cid: body.chapter_id, topics: added.map(a => ({ id: a.id, title: a.title, position: a.position })) });
  const edges = [];
  added.forEach(a => a.prereqs.forEach(p => { if (posToId[p]) edges.push({ from: posToId[p], to: a.id }); }));
  if (edges.length)
    await cypher(ctx, "UNWIND $edges AS e MATCH (a:Topic {id: e.from}), (b:Topic {id: e.to}) MERGE (a)-[:REQUIRED_FOR]->(b)", { edges });

  return json({ added: added.length, topics: added.map(a => a.title) }, 200);
}

// Append ONE new topic to an existing chapter (user-requested "add topics to a course").
async function opAddTopic(ctx, body) {
  if (!body.chapter_id || !body.topic) return json({ error: "chapter_id and topic required" }, 400);
  const ch = await ctx.db.query("SELECT id, title, grade_band FROM chapters WHERE id = $1", [body.chapter_id]);
  if (!ch.rows.length) return json({ error: "chapter not found" }, 404);
  const existing = await ctx.db.query(
    "SELECT position, title FROM topics WHERE chapter_id = $1 ORDER BY position", [body.chapter_id]);

  const prompt = [
    "You are extending a study chapter titled \\"" + ch.rows[0].title + "\\" (grade band " + ch.rows[0].grade_band + ").",
    "Existing topics in order: " + existing.rows.map(t => t.position + ": " + t.title).join("; "),
    "Create ONE new topic about: " + body.topic,
    "Output EXACTLY this JSON:",
    '{"title": "...", "key_idea": "one punchy sentence", "summary": "2-3 simple sentences", "explanation": "4-7 sentences in easy words with ONE concrete worked example or analogy", "illustration_prompt": "a purely visual scene, NO text in it", "prereqs": [positions of existing topics that should be understood first, or empty]}',
    "Output ONLY the JSON."
  ].join("\\n");
  const data = await llm(ctx, [{ role: "user", content: prompt }], { max_tokens: 1200, temperature: 0.3 });
  const t = parseJson(data.choices[0].message.content || "");
  if (!t.title || !t.explanation) return json({ error: "topic generation malformed — try again" }, 502);

  const pos = existing.rows.length ? Math.max(...existing.rows.map(r => r.position)) + 1 : 0;
  const validPrereqs = (t.prereqs || []).filter(p => existing.rows.some(r => r.position === p));
  const r = await ctx.db.query(
    "INSERT INTO topics (chapter_id, position, title, key_idea, summary, explanation, illustration_prompt, prereqs) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id",
    [body.chapter_id, pos, t.title, t.key_idea || "", t.summary || "", t.explanation, t.illustration_prompt || t.title, JSON.stringify(validPrereqs)]
  );
  const topicId = r.rows[0].id;

  await cypher(ctx,
    "MATCH (c:Chapter {id: $cid}) MERGE (n:Topic {id: $tid}) ON CREATE SET n.mastered = false " +
    "SET n.title = $title, n.position = $pos, n.chapter = c.title MERGE (c)-[:HAS_TOPIC]->(n)",
    { cid: body.chapter_id, tid: topicId, title: t.title, pos });
  if (validPrereqs.length) {
    const ids = await ctx.db.query(
      "SELECT id FROM topics WHERE chapter_id = $1 AND position = ANY($2::int[])",
      [body.chapter_id, validPrereqs]);
    await cypher(ctx,
      "UNWIND $edges AS e MATCH (a:Topic {id: e.from}), (b:Topic {id: e.to}) MERGE (a)-[:REQUIRED_FOR]->(b)",
      { edges: ids.rows.map(x => ({ from: x.id, to: topicId })) });
  }
  return json({ topic_id: topicId, title: t.title, position: pos }, 200);
}

async function opIllustrate(ctx, body) {
  const r = await ctx.db.query("SELECT id, title, key_idea, illustration_prompt, image FROM topics WHERE id = $1", [body.topic_id]);
  if (!r.rows.length) return json({ error: "topic not found" }, 404);
  const t = r.rows[0];
  if (t.image) return json({ image: t.image, cached: true }, 200);

  const data = await llm(ctx, [{
    role: "user",
    content: "A warm hand-drawn colored-pencil educational illustration on cream paper, notebook-sketch style with soft blue and yellow accents, friendly and clear, absolutely NO words, letters, numbers or labels anywhere in the image. Scene: " + (t.illustration_prompt || t.title) + " — visually conveying: " + t.key_idea
  }], { model: "google/gemini-3.1-flash-image", max_tokens: 2500 });

  const img = data.choices?.[0]?.message?.images?.[0]?.image_url?.url;
  if (!img || !img.startsWith("data:image/")) return json({ error: "no image returned" }, 502);
  await ctx.db.query("UPDATE topics SET image = $1 WHERE id = $2", [img, body.topic_id]);
  return json({ image: img }, 200);
}

async function opPack(ctx, body) {
  const r = await ctx.db.query(
    "SELECT t.id, t.title, t.explanation, t.key_idea, t.pack, c.grade_band FROM topics t JOIN chapters c ON c.id = t.chapter_id WHERE t.id = $1",
    [body.topic_id]);
  if (!r.rows.length) return json({ error: "topic not found" }, 404);
  const t = r.rows[0];
  if (t.pack) return json({ pack: t.pack, cached: true }, 200);

  const prompt = PACK_GEN_TEMPLATE
    .replace("{{TOPIC}}", t.title + " — " + t.key_idea + ". Reference explanation: " + t.explanation)
    .replace("{{GRADE_BAND}}", t.grade_band || "6-8")
    .replace("{{EXAMPLE_PACK_JSON}}", JSON.stringify(EXAMPLE_PACK, null, 2));
  const data = await llm(ctx, [{ role: "user", content: prompt }], { max_tokens: 2500, temperature: 0.4 });
  const pack = parseJson(data.choices[0].message.content || "");
  if (!pack.misconceptions || pack.misconceptions.length !== 3 || !pack.check_problem)
    return json({ error: "pack generation malformed — try again" }, 502);
  pack.id = "topic_" + t.id;
  await ctx.db.query("UPDATE topics SET pack = $1 WHERE id = $2", [JSON.stringify(pack), body.topic_id]);
  return json({ pack }, 200);
}

// Real-world applications: 4 "where you'd actually meet this" scenarios per topic.
// LLM text only — costs fractions of a cent; cached forever on the topic row.
async function opApplications(ctx, body) {
  const r = await ctx.db.query(
    "SELECT t.id, t.title, t.key_idea, t.explanation, t.applications, c.grade_band FROM topics t JOIN chapters c ON c.id = t.chapter_id WHERE t.id = $1",
    [body.topic_id]);
  if (!r.rows.length) return json({ error: "topic not found" }, 404);
  const t = r.rows[0];
  if (t.applications) return json({ applications: t.applications, cached: true }, 200);

  const prompt = [
    "Topic: " + t.title + " — " + t.key_idea,
    "Grade band: " + (t.grade_band || "6-8") + ". Reference explanation: " + t.explanation,
    "",
    "Give EXACTLY 4 real-world places a student genuinely meets this concept — vivid, specific, surprising where possible.",
    "Each one: a place/scenario the student recognizes, and HOW the concept is doing the work there, in 2 short punchy sentences a kid would enjoy reading.",
    'Output EXACTLY: {"applications": [{"emoji": "one fitting emoji", "where": "3-6 word place/scenario", "how": "2 punchy sentences"}]}',
    "Output ONLY the JSON."
  ].join("\\n");
  const data = await llm(ctx, [{ role: "user", content: prompt }], { max_tokens: 900, temperature: 0.5 });
  const out = parseJson(data.choices[0].message.content || "");
  if (!Array.isArray(out.applications) || out.applications.length < 3)
    return json({ error: "applications malformed — try again" }, 502);
  await ctx.db.query("UPDATE topics SET applications = $1 WHERE id = $2", [JSON.stringify(out.applications.slice(0, 4)), body.topic_id]);
  return json({ applications: out.applications.slice(0, 4) }, 200);
}

// Reels: short vertical concept videos (TikTok-style learning). Generation costs
// real credits (~$1/clip) so it's on-demand and cached forever on the topic row.
async function opReelStart(ctx, body) {
  const r = await ctx.db.query("SELECT id, title, key_idea, illustration_prompt, video FROM topics WHERE id = $1", [body.topic_id]);
  if (!r.rows.length) return json({ error: "topic not found" }, 404);
  const t = r.rows[0];
  if (t.video) return json({ cached: true }, 200);

  const model = body.model === "veo" ? "google/veo-3.1-fast" : "bytedance/seedance-2.0-fast";
  const res = await fetch(ctx.env.BUTTERBASE_API_URL + "/v1/" + ctx.env.BUTTERBASE_APP_ID + "/videos/completions", {
    method: "POST",
    headers: { "content-type": "application/json", authorization: "Bearer " + ctx.env.BUTTERBASE_API_KEY },
    body: JSON.stringify({
      model,
      prompt: "Hand-drawn colored pencil educational animation on cream paper, notebook sketch style, warm and friendly, soft blue and yellow accents, NO words or letters anywhere. Vertical composition. Scene showing: " + (t.illustration_prompt || t.title) + " — visually conveying: " + t.key_idea,
      duration: 4, resolution: "720p", aspect_ratio: "9:16"
    })
  });
  if (!res.ok) return json({ error: "video submit " + res.status + ": " + (await res.text()).slice(0, 150) }, 502);
  const job = await res.json();
  return json({ job_id: job.job_id, status: job.status }, 200);
}

async function opReelPoll(ctx, body) {
  if (!body.topic_id || !body.job_id) return json({ error: "topic_id and job_id required" }, 400);
  const res = await fetch(ctx.env.BUTTERBASE_API_URL + "/v1/" + ctx.env.BUTTERBASE_APP_ID + "/videos/completions/" + body.job_id, {
    headers: { authorization: "Bearer " + ctx.env.BUTTERBASE_API_KEY }
  });
  if (!res.ok) return json({ error: "poll " + res.status }, 502);
  const st = await res.json();
  if (st.status === "failed") return json({ status: "failed", error: st.error }, 200);
  if (st.status !== "completed") return json({ status: st.status }, 200);

  const vid = await fetch(st.content_urls[0], { headers: { authorization: "Bearer " + ctx.env.BUTTERBASE_API_KEY } });
  const buf = new Uint8Array(await vid.arrayBuffer());
  let bin = "";
  for (let i = 0; i < buf.length; i += 0x8000) bin += String.fromCharCode.apply(null, buf.subarray(i, i + 0x8000));
  const dataUri = "data:video/mp4;base64," + btoa(bin);
  await ctx.db.query("UPDATE topics SET video = $1 WHERE id = $2", [dataUri, body.topic_id]);
  return json({ status: "completed", charged: st.charged_credits_usd }, 200);
}

// The class companion: one EverMind agent that follows the whole class. It reads
// the aggregated evidence, advises the teacher, and writes an encouragement for
// each student. Its own memory of the class accumulates in EverOS across runs.
async function opCoach(ctx, body) {
  if (!body.digest) return json({ error: "digest required" }, 400);

  const prompt = [
    "You are the CLASS COMPANION for a classroom where students prove understanding by teaching AI proteges.",
    "You have followed this class across sessions. Here is today's evidence digest (computed from real sessions):",
    JSON.stringify(body.digest, null, 1).slice(0, 6000),
    "",
    "Skills are 0-100 heuristics: communication (explains at length, uses examples), clarity (explanations actually resolve confusions), confidence (rarely hedges or answers in fragments — low = possible fear/anxiety).",
    "Write for a busy teacher, concrete and kind. Output EXACTLY:",
    '{"read": "one sentence on where the class is", "suggestions": ["3 specific, actionable teaching moves tied to the digest"], "encouragements": [{"student": "first name", "note": "1-2 sentences the teacher can pass on, referencing something real that student did"}]}',
    "Never invent students or facts not in the digest. Output ONLY the JSON."
  ].join("\\n");

  const data = await llm(ctx, [{ role: "user", content: prompt }], { max_tokens: 1200, temperature: 0.4 });
  const out = parseJson(data.choices[0].message.content || "");
  if (!out.read || !Array.isArray(out.suggestions)) return json({ error: "coach output malformed" }, 502);

  // The companion remembers the class in EverOS (non-fatal if unavailable).
  if (ctx.env.EVEROS_API_KEY) {
    try {
      const now = Date.now();
      await fetch("https://api.evermind.ai/api/v1/memories", {
        method: "POST",
        headers: { "content-type": "application/json", authorization: "Bearer " + ctx.env.EVEROS_API_KEY },
        body: JSON.stringify({
          user_id: "class_companion",
          session_id: "class_" + new Date().toISOString().slice(0, 10),
          async_mode: false,
          messages: [
            { role: "user", timestamp: now, content: "Class digest: " + JSON.stringify(body.digest).slice(0, 3000) },
            { role: "assistant", timestamp: now + 1000, content: "My read: " + out.read + " Advice given: " + out.suggestions.join(" | ") }
          ]
        })
      });
      await fetch("https://api.evermind.ai/api/v1/memories/flush", {
        method: "POST",
        headers: { "content-type": "application/json", authorization: "Bearer " + ctx.env.EVEROS_API_KEY },
        body: JSON.stringify({ user_id: "class_companion" })
      });
    } catch (err) { console.warn("companion everos write failed:", err.message); }
  }

  return json(out, 200);
}

async function opMastered(ctx, body) {
  await ctx.db.query("UPDATE topics SET mastered = true WHERE id = $1", [body.topic_id]);
  await cypher(ctx, "MATCH (t:Topic {id: $id}) SET t.mastered = true", { id: body.topic_id });
  return json({ ok: true }, 200);
}

async function opNext(ctx) {
  const data = await cypher(ctx,
    "MATCH (t:Topic) WHERE t.mastered = false AND NOT EXISTS { MATCH (p:Topic)-[:REQUIRED_FOR]->(t) WHERE p.mastered = false } " +
    "RETURN t.id AS id, t.title AS title, t.chapter AS chapter ORDER BY t.position LIMIT 6");
  if (!data) return json({ next: [] }, 200);
  const idx = { id: data.fields.indexOf("id"), title: data.fields.indexOf("title"), chapter: data.fields.indexOf("chapter") };
  return json({ next: data.values.map(v => ({ id: v[idx.id], title: v[idx.title], chapter: v[idx.chapter] })) }, 200);
}

export default async function handler(req, ctx) {
  if (req.method === "OPTIONS") return new Response(null, { status: 204, headers: CORS });
  if (req.method !== "POST") return json({ error: "POST only" }, 405);
  try {
    const body = await req.json();
    switch (body.op) {
      case "chapter":    return await opChapter(ctx, body);
      case "add_topic":  return await opAddTopic(ctx, body);
      case "extend":     return await opExtend(ctx, body);
      case "applications": return await opApplications(ctx, body);
      case "coach":      return await opCoach(ctx, body);
      case "reel_start": return await opReelStart(ctx, body);
      case "reel_poll":  return await opReelPoll(ctx, body);
      case "illustrate": return await opIllustrate(ctx, body);
      case "pack":       return await opPack(ctx, body);
      case "mastered":   return await opMastered(ctx, body);
      case "next":       return await opNext(ctx);
      default:           return json({ error: "unknown op: " + body.op }, 400);
    }
  } catch (err) {
    return json({ error: String((err && err.message) || err) }, 500);
  }
}
`;

mkdirSync(join(root, "functions"), { recursive: true });
writeFileSync(join(root, "functions", "learn.built.js"), code);
console.log(`functions/learn.built.js written (${code.length} bytes)`);
